'''Generated by Django 4.2.3 on 2023-07-23 09:03'''

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    '''Create VPNS table'''
    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='servers.servers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='users.users')),
            ],
            options={
                'indexes': [models.Index(fields=['finished_at'],
                                         name='vpn_vpns_finishe_001c6c_idx')],
            },
        ),
    ]
