# Generated by Django 4.2.3 on 2023-07-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('payload', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('price_label', models.CharField(max_length=50)),
                ('price_amount', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.servers')),
            ],
        ),
        migrations.CreateModel(
            name='SUBSCRIPTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.vpns')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'indexes': [models.Index(fields=['finished_at'], name='vpn_subscri_finishe_5a6a39_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO vpn_vpns (id, name, server_id, description, payload, currency, price_label, price_amount)
            VALUES (1, 'Нидерланды', 1, 'Доступ к VPN Нидерланды (месяц)', 'vpn_niderlands_mounth', 'RUB', 'Подписка на месяц', 100);
            """,
            reverse_sql="""
            DELETE FROM vpn_vpns where id=1;
            """,
        ),
    ]
