'''Generated by Django 4.2.3 on 2023-07-23 09:03'''

from django.db import migrations, models


class Migration(migrations.Migration):
    '''Create table USERS'''
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('tg_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tg_link', models.CharField(max_length=200)),
                ('tg_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
